---
- hosts: localhost
  user: root
  tasks:     
    - name: create venv
      shell: python3 -m venv /opt/python_venvs/testvenv1
      shell: ls
      
    - name: venv activate
      shell: source /opt/python_venvs/testvenv1/bin/activate
      args:
       executable: /bin/bash
      shell: python3 -V
      
    - name: Check if output directory exists
      file:
       path: /opt/python_venvs/test2
       state: directory
       
      
    - name: requirement
      shell: pip install -r requirements.txt
      
    - name: ansible version
      shell: which ansible
      shell: python3 -m pip list
    
