---
- hosts: localhost
  user: root
  tasks:     
    - name: create venv
      shell: python3 -m venv /opt/python_venvs/testvenv1
      shell: ls
      
    - name: venv activate
      shell: source /opt/python_venvs/testvenv1/bin/activate
      args:
       executable: /bin/bash
      shell: python3 -V
      
    - name: Create directory
      file:
       path: /opt/python_venvs/test2
       state: directory
       
    - name: Check if a file exists
      stat:
       path: /opt/python_venvs/testvenv1
      register: file_data
      
    - name: report if a file exists
      debug:
       msg: "the file is exist"
      when: file_data.stat.exist
      
    - name: report missing file
      debug:
       msg: "the file is not exist"
      when: not file_data.stat.exist
          
      
    - name: requirement
      shell: pip install -r requirements.txt
      
    - name: ansible version
      shell: which ansible
      shell: python3 -m pip list
    
