---
- hosts: localhost
  user: root
  tasks:     
    - name: create venv
      shell: python3 -m venv /opt/python_venvs/testvenv1

    - name: venv activate
      shell: source /opt/python_venvs/testvenv1/bin/activate
      args:
       executable: /bin/bash
      
    - name: requirement
      shell: pip install -r requirements.txt
    
