---
- hosts: localhost
  user: root

  tasks:

    # first ensure our target directory exists
    - name: Ensure target directory exists
      file:
        dest: "./venvs"
        state: directory
    # get each txt file 
    - name: Get each txt file and create venvs
      shell: python3 -m venv /opt/python-venv/"{{ item | basename | splitext | first  }}"
      shell: source /opt/python-venv/"{{ item | basename | splitext | first  }}"/bin/activate
      args:
       executable: /bin/bash
      with_fileglob: "./venvs/*.txt"
    - name: list venvs
      shell: ls -al /opt/python-venv/
