---
- hosts: localhost
  user: root
  tasks: 
    - name: install pip
      easy_install: name=pip

    - name: install virtualenv
      pip: name=virtualenv
      
    - name: create venv
      shell: python3 -m venv /opt/python_venvs/testvenv1
      shell: ls
      
    - name: venv activate
      shell: source /opt/python_venvs/testvenv1/bin/activate
      args:
       executable: /bin/bash
      shell: python3 -V
      
    - name: Create directory
      file:
       path: /opt/python_venvs/test2
       state: directory
       
    - name: Check if a directory exists
      stat:
       path: /opt/python_venvs/test2
      register: dir_to_check
      
    - name: Directory found
      debug:
       msg: "Directory present"
      when: dir_to_check.stat.exists and dir_to_check.stat.isdir
      
    - name: Check if a file exists
      stat:
       path: /opt/python_venvs/testvenv1
      register: file_data
      
    - name: file found
      debug:
       msg: "File present"
      when: file_data.stat.exists
      
    - name: file not found
      debug:
       msg: "File not found"
      when: not file_data.stat.exists

          
      
    - name: requirement
      shell: pip install -r requirements.txt
      
    - name: ansible version
      shell: which ansible
      shell: python3 -m pip list
    
