---
- hosts: localhost
  user: root

  tasks:
    # first ensure our target directory exists
    - name: Ensure target directory exists
      file:
        dest: "./venvs"
        state: directory
    - name: Create venv dir if it does not exist
      ansible.builtin.file:
       path: /opt/python_venvs/
       state: directory
       mode: '0755'
    - name: Check if a directory exists
      stat:
       path: /opt/python_venvs/
      register: dir_to_check

    - name: Directory found
      debug:
       msg: "Directory present"
      when: dir_to_check.stat.exists and dir_to_check.stat.isdir



    # get each txt file
    - name: Get each txt file and create venvs
      shell: python3 -m venv /opt/python_venvs/"{{ item | basename | splitext | first  }}" && cp ./venvs/"{{ item | basename }}" /opt/python_venvs/"{{ item | basename | splitext | first  }}"  && source /opt/python_venvs/"{{ item | basename | splitext | first  }}"/bin/activate && pip install -r /opt/python_venvs/"{{ item | basename | splitext | first  }}"/{{ item | basename}}
      args:
       executable: /bin/bash
      with_fileglob: "./venvs/*.txt"
