name: Python application
on:
 push:
  branches:
   - main
jobs:
 ansible:
  runs-on: ubuntu-18.04
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
     python-version: "3.10"
  - name: Install dependencies
    run: |
     python -m pip install --upgrade pip
     mkdir /opt/python_venvs/
     cd /opt/python_venvs/
     mkdir ansible
     ls -al
     pwd
     echo "${GITHUB_WORKSPACE}"
  - name: Run playbook
    uses: dawidd6/action-ansible-playbook@v2
    with:
     playbook: deploy.yml
     directory: ./
  - name: ansible
    run: |
     pwd
     ls -al /opt/python_venvs/
     python3 -V
     ls -al
     which ansible
     python3 -m pip list
     echo "${GITHUB_WORKSPACE}"
  - name: run test.sh
    run: |
     chmod +x "${GITHUB_WORKSPACE}/test.sh"
     ${GITHUB_WORKSPACE}/test.sh
   
